/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'STM32F407VET6' 
 * Target:  'STM32F407VET6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"

/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.1.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.1.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.1.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.1.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.1.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.1.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Keil::Device:STM32Cube Framework:Classic@1.8.1 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:ADC@1.8.1 */
#define RTE_DEVICE_HAL_ADC
/* Keil::Device:STM32Cube HAL:CAN@1.8.1 */
#define RTE_DEVICE_HAL_CAN
/* Keil::Device:STM32Cube HAL:CRC@1.8.1 */
#define RTE_DEVICE_HAL_CRC
/* Keil::Device:STM32Cube HAL:Common@1.8.1 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.8.1 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DAC@1.8.1 */
#define RTE_DEVICE_HAL_DAC
/* Keil::Device:STM32Cube HAL:DCMI@1.8.1 */
#define RTE_DEVICE_HAL_DCMI
/* Keil::Device:STM32Cube HAL:DMA@1.8.1 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:ETH@1.8.1 */
#define RTE_DEVICE_HAL_ETH
/* Keil::Device:STM32Cube HAL:EXTI@1.8.1 */
#define RTE_DEVICE_HAL_EXTI
/* Keil::Device:STM32Cube HAL:Flash@1.8.1 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device:STM32Cube HAL:GPIO@1.8.1 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:HCD@1.8.1 */
#define RTE_DEVICE_HAL_HCD
/* Keil::Device:STM32Cube HAL:I2C@1.8.1 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device:STM32Cube HAL:I2S@1.8.1 */
#define RTE_DEVICE_HAL_I2S
/* Keil::Device:STM32Cube HAL:IRDA@1.8.1 */
#define RTE_DEVICE_HAL_IRDA
/* Keil::Device:STM32Cube HAL:IWDG@1.8.1 */
#define RTE_DEVICE_HAL_IWDG
/* Keil::Device:STM32Cube HAL:MMC@1.8.1 */
#define RTE_DEVICE_HAL_MMC
/* Keil::Device:STM32Cube HAL:NAND@1.8.1 */
#define RTE_DEVICE_HAL_NAND
/* Keil::Device:STM32Cube HAL:NOR@1.8.1 */
#define RTE_DEVICE_HAL_NOR
/* Keil::Device:STM32Cube HAL:PC Card@1.8.1 */
#define RTE_DEVICE_HAL_PCCARD
/* Keil::Device:STM32Cube HAL:PCD@1.8.1 */
#define RTE_DEVICE_HAL_PCD
/* Keil::Device:STM32Cube HAL:PWR@1.8.1 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.8.1 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:RNG@1.8.1 */
#define RTE_DEVICE_HAL_RNG
/* Keil::Device:STM32Cube HAL:RTC@1.8.1 */
#define RTE_DEVICE_HAL_RTC
/* Keil::Device:STM32Cube HAL:SD@1.8.1 */
#define RTE_DEVICE_HAL_SD
/* Keil::Device:STM32Cube HAL:SMBUS@1.8.1 */
#define RTE_DEVICE_HAL_SMBUS
/* Keil::Device:STM32Cube HAL:SPI@1.8.1 */
#define RTE_DEVICE_HAL_SPI
/* Keil::Device:STM32Cube HAL:SRAM@1.8.1 */
#define RTE_DEVICE_HAL_SRAM
/* Keil::Device:STM32Cube HAL:Smartcard@1.8.1 */
#define RTE_DEVICE_HAL_SMARTCARD
/* Keil::Device:STM32Cube HAL:TIM@1.8.1 */
#define RTE_DEVICE_HAL_TIM
/* Keil::Device:STM32Cube HAL:UART@1.8.1 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:STM32Cube HAL:USART@1.8.1 */
#define RTE_DEVICE_HAL_USART
/* Keil::Device:STM32Cube HAL:WWDG@1.8.1 */
#define RTE_DEVICE_HAL_WWDG
/* Keil::Device:Startup@2.6.3 */
#define RTE_DEVICE_STARTUP_STM32F4XX    /* Device Startup for STM32F4 */
/* LVGL::LVGL&LVGL:lvgl:Essential@8.4.0 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL


#endif /* RTE_COMPONENTS_H */
